package html.parser;

public enum TokensId {
    TEXT, HTMLA, HTMLB,H1A, H1B, H2A, H2B, H3A, H3B, HEADA, HEADB, TITLEA, TITLEB, PA, PB, BA, BB,
    URL, IA, IB, UA, UB, LINKA, LINKB, IGUAL, HREF, REL, TYPE, BODYA, BODYB, EOF
}
